enabled: true
cardstack_route: /cards
default_lang: en
continueLinkIcon: exclamation-circle
cardview:
  columns:
    small: '1'
    medium: '2'
    large: '3'
    xlarge: '3'
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/cardstack
